language: java

dist: xenial

jdk: openjdk8

git:
  depth: false

addons:
  sonarcloud:
    organization: "alessandroferi-github"
    
services:
  - xvfb

 # skip installation step
install: true

cache:
   directories:
      - $HOME/.m2
      - $HOME/.sonar/cache

script:
  - mvn -f spring-testing-exercise/pom.xml clean verify -Pjacoco && mvn -f spring-testing-exercise/pom.xml verify -Pe2e-tests && mvn -f spring-testing-exercise/pom.xml coveralls:report sonar:sonar